modLoader="javafml"
loaderVersion="[47,)"
license="Nigga Lisence v3.0 By Hitler (jk)"

[[mods]]
modId="boss_music_mod"
version="69.42.0"
displayName="Boss Music Mod"
credits="Created By Kurokami Fubuki"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
authors="Kurokami Fubuki"

[[dependencies.boss_music_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




